"""Writes the simulator's set bonus table into Sim/SimItems.lua.

Every set bonus in Data/SetCatalog.lua is a spell in the Tortoise DB snapshot.
Plain stat auras (attack power, crit, hit, strength, agility, weapon skill,
attack speed, block, dodge, parry) become numbers the simulator adds directly.
Bonuses that only affect defence, spells, threat or other classes are marked
"none". Everything else (procs and ability modifiers) is listed by spell id so
the class modules can implement it or report it as not simulated.

usage: python tools/build_set_effects.py path/to/tortoise.sqlite
"""
import json, os, re, sqlite3, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = sys.argv[1] if len(sys.argv) > 1 else "tortoise.sqlite"

# Weapon skill lines -> the builder's weapon type names.
SKILLS = {43: "Sword", 44: "Axe", 54: "Mace", 55: "TwoHandSword", 160: "TwoHandMace", 172: "TwoHandAxe",
          173: "Dagger", 229: "Polearm", 473: "Fist", 136: "Staff"}
# Auras with no effect on melee damage done.
NO_DPS = {22, 13, 135, 197, 198, 85, 55, 71, 31, 58, 117, 10, 123, 134, 129, 168, 102, 131, 87, 77, 161,
          124, 140, 65, 72, 112, 23, 35, 183, 28, 4, 109, 47, 49, 51, 158, 142, 143}
STAT = {0: "str", 1: "agi"}

def main():
    db = sqlite3.connect(DB)
    catalog = open(os.path.join(ROOT, "Data", "SetCatalog.lua"), encoding="utf-8").read()
    spells = sorted({int(s) for s in re.findall(r'\{\d+,(\d+),"', catalog)})
    lines = []
    for sid in spells:
        row = db.execute("select name, effects from spells where entry=?", (sid,)).fetchone()
        if not row:
            continue
        effects = json.loads(row[1] or "[]")
        stats, skills, special, defensive = {}, {}, False, {}
        for e in effects:
            eff, aura, value, misc = e["effect"], e["aura"], e["value"], e["misc"]
            if eff != 6:
                special = True
            elif aura == 29 and misc in STAT:
                stats[STAT[misc]] = stats.get(STAT[misc], 0) + value
            elif aura == 29 and misc == -1:
                for k in ("str", "agi"): stats[k] = stats.get(k, 0) + value
            elif aura == 29:
                pass  # stamina / intellect / spirit
            elif aura == 99:
                stats["ap"] = stats.get("ap", 0) + value
            elif aura == 52:
                stats["crit"] = stats.get("crit", 0) + value
            elif aura == 54:
                stats["hit"] = stats.get("hit", 0) + value
            elif aura == 138:
                stats["haste"] = stats.get("haste", 0) + value
            elif aura in (107, 108) and misc in (2, 5, 6, 1):
                pass  # threat, range, radius or duration of an ability: no damage effect
            elif aura in (30, 98) and "all weapons" in row[0].lower():
                skills["all"] = skills.get("all", 0) + value   # Turtle "+N to All Weapons" (encoded as skill 162)
            elif aura in (30, 98):
                if misc in SKILLS:
                    skills[SKILLS[misc]] = skills.get(SKILLS[misc], 0) + value
                elif misc == 95 or misc not in SKILLS and misc > 0:
                    pass  # defense or non-weapon skills
                else:
                    skills["all"] = skills.get("all", 0) + value
            elif aura in NO_DPS:
                pass
            else:
                special = True
        parts = ["%s=%s" % (k, fmt(v)) for k, v in sorted(stats.items())]
        if skills:
            parts.append("skill={%s}" % ",".join("%s=%s" % (k, fmt(v)) for k, v in sorted(skills.items())))
        if special:
            parts.append("special=true")
        if not parts:
            parts.append("none=true")
        lines.append("E[%d]={%s} -- %s" % (sid, ",".join(parts), row[0].replace("\n", " ")))
    path = os.path.join(ROOT, "Sim", "SimItems.lua")
    text = open(path, encoding="utf-8").read()
    begin, end = "-- BEGIN GENERATED SET EFFECTS", "-- END GENERATED SET EFFECTS"
    block = (begin + "\n-- Generated by tools/build_set_effects.py from the Tortoise DB. Do not edit by hand.\n"
             "local E = {}\nS.SetEffects = E\n" + "\n".join(lines) + "\n" + end)
    if begin in text:
        text = text[:text.index(begin)] + block + text[text.index(end) + len(end):]
    else:
        text = text.rstrip("\n") + "\n\n" + block + "\n"
    open(path, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote", len(lines), "set bonus spells")

def fmt(v):
    return str(int(v)) if float(v).is_integer() else str(v)

if __name__ == "__main__":
    main()
